# Generated by Django 3.2.8 on 2021-11-25 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.CharField(max_length=500, verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('location', models.CharField(max_length=100, verbose_name='Местонахождение')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('achievement', models.CharField(max_length=500, verbose_name='Достижение')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.status', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('points', models.IntegerField(verbose_name='Количество баллов')),
                ('role', models.CharField(max_length=20, verbose_name='Роль')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
