# Generated by Django 3.2.7 on 2021-10-14 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20211014_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='creator_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
