# Generated by Django 3.2.8 on 2021-10-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20211014_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создател'),
        ),
    ]
