# Generated by Django 3.2.8 on 2021-11-03 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_alter_task_creator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('points', models.IntegerField(default='0000000', editable=False, verbose_name='Количество баллов')),
                ('role', models.CharField(default='user', editable=False, max_length=20, verbose_name='Роль')),
                ('rating', models.IntegerField(default='0000000', editable=False, verbose_name='Рейтинг')),
                ('code', models.CharField(default='0000', editable=False, max_length=256, verbose_name='Код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
