# Generated by Django 3.2.8 on 2021-10-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_useradd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradd',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
