# Generated by Django 3.2.8 on 2021-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(editable=False, max_length=256, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(editable=False, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(editable=False, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(editable=False, max_length=20, verbose_name='Роль'),
        ),
    ]
