# Generated by Django 3.2.8 on 2021-10-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_useradd_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useradd',
        ),
    ]
