# Generated by Django 3.2.8 on 2021-10-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
