# Generated by Django 3.2.8 on 2021-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(verbose_name='Количество баллов'),
        ),
    ]
