# Generated by Django 3.2.8 on 2021-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_task_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
