# Generated by Django 3.2.8 on 2021-11-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_task_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.DO_NOTHING, to='todo.status', verbose_name='Статус'),
        ),
    ]
