# Generated by Django 3.2.8 on 2021-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(default='0000', editable=False, max_length=256, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default='0000000', editable=False, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', editable=False, max_length=20, verbose_name='Роль'),
        ),
    ]
