# Generated by Django 3.2.8 on 2021-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_task_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
    ]
