# Generated by Django 3.2.8 on 2021-11-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_id',
            field=models.IntegerField(default=1, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
