# Generated by Django 3.2.8 on 2021-11-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
    ]
