# Generated by Django 3.2.8 on 2021-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
    ]
