# Generated by Django 3.2.8 on 2021-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_taskdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='achievement',
            field=models.CharField(default=1, max_length=500, verbose_name='Достижение'),
            preserve_default=False,
        ),
    ]
